<?php
$lang = array(
    // menus and homepage
    'dashboard' => 'dashboard',
    'product' => 'product',
    'addproduct' => 'add product',
    'manageproduct' => 'manage product',
    'stockmanagement' => 'stock management',
    'stock' => 'stock',
    'addstock' => 'add stock',
    'managestock' => 'manage stock',
    'sales' => 'sales',
    'addsales' => 'add sales',
    'managesales' => 'manage sales',
    'debt' => 'debt',
    'addclient' => 'add client',
    'manageclient' => 'manage client',
    'managedebts' => 'manage debts',
    'salesreport' => 'sales report',
    'dailyreport' => 'daily report',
    'monthlyreport' => 'monthly report',
    'rangereport' => 'range report',
    'account' => 'account',
    'logout' => 'logout',
    'accountprivilages' => 'account privilages',
    'abletomanageproduct' => 'You Are Able To Manage Products',
    'sellproducts' => 'sell products',
    'abletosellproduct' => 'You are able  to sell products',
    'managedebts'=>'manage debts',
    'abletomanagedebts' => 'You are able to manage debts',
    'notifications' => 'notifications',
        //notifications
    'withphone' => ' With Phone ',
    'remains' => ' Remains ',
    'days' => ' Days ',
    'day' => ' Day ',
    'topaydebtof' => ' To Pay Debt Of ',
    'takenon' => ' Taken On ',
    'willpay' => ' Will Pay ',
    'today' => ' Today ',
    'debtof' => ' Debt Of ',
    // navbar
    'manager' => 'Manager',
    'seller' => 'Seller',
    'settings' => 'Settings',
    // newproduct.php
    'productname' => 'Product Name',
    'quality' => 'quality',
    'manufacturer' => 'Manufacturer',
    'save' => 'Save',
    // viewproduct.php
    'yes' => 'yes',
    'no' => 'no',
    'suredeleteproduct' => 'are you sure you want to delete product?',
    'actions' => 'Actions',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'updateproduct' => 'Update Product',
    'addstock' => 'Add Stock',
    'selectproduct' => 'Select Product',
    'stquality' => ' Quality ',
    'stmanufacturer' => ' Manufactured By ',
    'quantity' => 'Quantity',
    'unitprice' => 'Unit Price',
    'sellprice' => 'Sell Price',
    'expiration' => 'Expiration Date',
    'stockinsucess'=> 'Stock In Done Successful',
       // viewstockin.php
    'suredeletestockin' => 'are you sure you want to delete stock In record?',
    'totalprice' => 'Total Price',
    'totalincome' => 'Total Income',
    'dateregistered' => 'Date Registered',
    'interest' => 'Interest',
    'done' => 'Action Completed',
    'updatedata' => 'Update Data',
    // newstockout.php
    'checkproductavailability' => 'Check product availability first',
    'selectquality' => 'Select Quality',
    'selectmanufacturer' => 'Select Manufacturer',
    'check' => 'Check',
    'clicktochangeproduct' => 'Click to change product',
    'availablequantityinsctock' => 'Available Quantity In Stock',
    'price' => 'Price',
    'stoutquantity' => 'Quantity Out',
    'amounttopay' => 'Amount to pay',
    'payment' => 'payment',
    'cash' => 'Cash',
    'debtpay' => 'Debt',
    'selectclient' => 'Select Client',
    'paymentdate' => 'Payment Date',
    'clientname' => 'Client Name',
    'phone' => 'Phone',
    'CLaleadyexist' => ' Already Exist',
    'cancel' => 'Cancel',
    // view stock out
    'dateandtimesold' => 'Date & Time Sold',
    'quantitysold' => 'Quantity Sold',
    'paidamount'=>'Paid Amount',
    'totalamount'=>'Total price',
    'comment'=>'Comment',
    'status'=>'Status',
    'timehaspassed'=>'time has passed',
    'willbepaidtoday'=>'will be payed today',
    'timenotreached'=>'time not reached',
    'dnotpaid'=>'Not Paid',
    'dpaid'=>'Paid',
    'markedaspaid'=>'Debt Marked As Paid',
    'markedasnotpaid'=>'Debt Marked As Not Paid',
    'sold'=>'Sold',
    'remaining'=>'Remaining',
    'income'=>'Income',
    'haspaid'=>'Paid',
    'purchase'=>'Purchase',
    'purchaseamount'=>'Purchase Amount',
    'expectedincome'=>'Expected Income',
    'total'=>'Total',
    'confirmpassword'=>'CONFIRM PASSWORD TO CONTINUE',
    'profiledetails'=>'Profile Details',
    'uploadphoto'=>'Upload a new photo',
    'alowed'=>'Allowed',
    'or'=>'or',
    'names'=>'Names',
    'privilage'=>'Privilage/Type',
    'password'=>'Password',
    'rangereportparagraph'=>'select dates to get report',
    'fromdate'=>'from date',
    'todate'=>'to date',
    'designedby'=>'Designed By',
    'spent'=>'spent',
    'withoutpaying'=>' Days without paying debt of',

    







);
?>
